language: scala

scala:
  - 2.12.7

env:
  global:
    - JDK=oraclejdk8
    - AWS_REGION=us-west-2

before_script:
  - jdk_switcher use $JDK

script: sbt ++$TRAVIS_SCALA_VERSION clean stack/clean 'testOnly -- timefactor 10' 'stack/testOnly -- timefactor 10'
